# Generated by Django 4.2.2 on 2023-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_slideshow_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='city',
            field=models.CharField(choices=[('Bamenda', 'Bamenda'), ('Douala', 'Douala'), ('Yaounde', 'Yaounde'), ('Buea', 'Buea')], max_length=50),
        ),
    ]
